### ISSUE TITLE
Fingerprinting issue

### ISSUE THREAD

**Issue by NullRien** [daijro/camoufox#124]
### Describe the bug:

After i updated to the latest VS of camoufox i got this bug (i was originally on 4.4 i think)

```
Full error traceback for 1Z077V0E1245515466:
Traceback (most recent call last):
  File "/home/euphoria/Documents/github/shipment_manager/test.py", line 19, in scan
    async with AsyncCamoufox(
  File "/home/euphoria/Documents/github/shipment_manager/venv/lib/python3.11/site-packages/camoufox/async_api.py", line 31, in __aenter__
    self.browser = await AsyncNewBrowser(_playwright, **self.launch_options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/euphoria/Documents/github/shipment_manager/venv/lib/python3.11/site-packages/camoufox/async_api.py", line 88, in AsyncNewBrowser
    from_options = await asyncio.get_event_loop().run_in_executor(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/euphoria/Documents/github/shipment_manager/venv/lib/python3.11/site-packages/camoufox/utils.py", line 501, in launch_options
    fingerprint = generate_fingerprint(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/euphoria/Documents/github/shipment_manager/venv/lib/python3.11/site-packages/camoufox/fingerprints.py", line 135, in generate_fingerprint
    return FP_GENERATOR.generate(**config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/euphoria/Documents/github/shipment_manager/venv/lib/python3.11/site-packages/browserforge/fingerprints/generator.py", line 170, in generate
    partial_csp = self.partial_csp(
                  ^^^^^^^^^^^^^^^^^
  File "/home/euphoria/Documents/github/shipment_manager/venv/lib/python3.11/site-packages/browserforge/fingerprints/generator.py", line 246, in partial_csp
    filtered_values['screen'] = [
                                ^
  File "/home/euphoria/Documents/github/shipment_manager/venv/lib/python3.11/site-packages/browserforge/fingerprints/generator.py", line 251, in <listcomp>
    if self._is_screen_within_constraints(screen_string, screen)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/euphoria/Documents/github/shipment_manager/venv/lib/python3.11/site-packages/browserforge/fingerprints/generator.py", line 278, in _is_screen_within_constraints
    and screen['height'] >= (screen_options.min_height or 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'str' and 'int'
```

### To Reproduce:

```
from camoufox.async_api import AsyncCamoufox
import asyncio

async def scan():

    trk_num = '1Z077V0E1245515466'

    proxy_config = {
        'server': 'http://3.144.179.61:8661',
        'username': 'Ov8KRBmf',
        'password': 'XjEAFkKIwdnP'
    }
    try:
        async with AsyncCamoufox(
            headless=True, 
            proxy={
                'server': str(proxy_config['server']),
                'username': str(proxy_config['username']),
                'password': str(proxy_config['password'])
            },
            geoip=True
        ) as browser:
            page = await browser.new_page()
            
            await page.goto(f"https://www.ups.com/track?loc=en_US&tracknum={trk_num}&requester=ST/trackdetails", timeout=30000)

            await asyncio.sleep(10)
            await browser.close()
            success = True

    except Exception as e:
        import traceback
        print(f"\nFull error traceback for {trk_num}:")
        print(traceback.format_exc())

asyncio.run(scan())
```

### Version:

Pip package:    v0.4.7
Camoufox:       v133.0-beta.19 (Up to date!)

**Comment by NCGSolutions** [comment]
This looks like an issue with BrowserForge and the fingerprint data that's grabbed. To fix go to:

site-packages/browserforge/fingerprints/generator.py

and replace this function:

```
@staticmethod
def _is_screen_within_constraints(screen_string: str, screen_options: Screen) -> bool:
    """
    Checks if the given screen dimensions are within the specified constraints.
    """
    try:
        screen = orjson.loads(screen_string[len('*STRINGIFIED*'):])
        return (
            (screen.get('width', 0) >= (int(screen_options.min_width) if screen_options.min_width else 0)
            and screen.get('width', 0) <= (int(screen_options.max_width) if screen_options.max_width else 1e5)
            and screen.get('height', 0) >= (int(screen_options.min_height) if screen_options.min_height else 0)
            and screen.get('height', 0) <= (int(screen_options.max_height) if screen_options.max_height else 1e5))
        )
    except (ValueError, TypeError):
        return False
```

**Comment by NullRien** [comment]
Thank you that works perfectly

**Comment by daijro** [comment]
Hello,

To fix this, please update BrowserForge to the latest version:

```bash
pip install -U browserforge
```

This turned out to be an issue with Browserforge's upstream data being contaminated.

See here: https://github.com/daijro/browserforge/issues/17
