### ISSUE TITLE
Cannot run camoufox fetch [404]

### ISSUE THREAD

**Issue by pureraven** [daijro/camoufox#135]
### Describe the bug:
I cannot run camoufox fetch, 

```
camoufox fetch
Camoufox binaries up to date!
Current version: v133.0-beta.19
Traceback (most recent call last):
  File "/home/nick/Files/work/evt/evt-apps/shelf/pjfinder/.venv/bin/camoufox", line 8, in <module>
    sys.exit(cli())
             ~~~^^
  File "/home/nick/Files/work/evt/evt-apps/shelf/pjfinder/.venv/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/nick/Files/work/evt/evt-apps/shelf/pjfinder/.venv/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/nick/Files/work/evt/evt-apps/shelf/pjfinder/.venv/lib/python3.13/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/nick/Files/work/evt/evt-apps/shelf/pjfinder/.venv/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nick/Files/work/evt/evt-apps/shelf/pjfinder/.venv/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/nick/Files/work/evt/evt-apps/shelf/pjfinder/.venv/lib/python3.13/site-packages/camoufox/__main__.py", line 89, in fetch
    download_mmdb()
    ~~~~~~~~~~~~~^^
  File "/home/nick/Files/work/evt/evt-apps/shelf/pjfinder/.venv/lib/python3.13/site-packages/camoufox/locale.py", line 212, in download_mmdb
    webdl(
    ~~~~~^
        MMDB_URL,
        ^^^^^^^^^
        desc='Downloading GeoIP database',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        buffer=f,
        ^^^^^^^^^
    )
    ^
  File "/home/nick/Files/work/evt/evt-apps/shelf/pjfinder/.venv/lib/python3.13/site-packages/camoufox/pkgman.py", line 436, in webdl
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/nick/Files/work/evt/evt-apps/shelf/pjfinder/.venv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/P3TERX/GeoLite.mmdb/releases/download/2024.12.13/GeoLite2-City.mmdb
```

### Screenshots:

![Screenshot_20241213_121518](https://github.com/user-attachments/assets/4cd2f87f-b9df-469b-9f4c-7b935d3f8fde)

### To Reproduce:

only run, `camoufox fetch`

### Version:

Pip package:    v0.4.4
Camoufox:       v133.0-beta.19 (Up to date!)

**Comment by pureraven** [comment]
#134
