### ISSUE TITLE
Camoufox fetch error

### ISSUE THREAD

**Issue by chrisemke** [daijro/camoufox#136]
### Describe the bug:

When trying to run camoufox fetch inside of container and outside it's having this issue

### Screenshots:

Traceback:
```
❯ camoufox fetch
Fetching Camoufox binaries v133.0-beta.19...
Downloading package: https://github.com/daijro/camoufox/releases/download/v133.0-beta.19/camoufox-133.0-beta.19-mac.arm64.zip
100%|██████████████████████████████████████████████████████████████████████████| 295M/295M [00:09<00:00, 32.7MiB/s]
Extracting Camoufox: /Users/krisque/Library/Caches/camoufox
100%|███████████████████████████████████████████████████████████████████████████| 399/399 [00:01<00:00, 255.42it/s]

Camoufox successfully installed.
Traceback (most recent call last):
  File "/Users/krisque/Knowtrex/opony/.venv/bin/camoufox", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/krisque/Knowtrex/opony/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krisque/Knowtrex/opony/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/krisque/Knowtrex/opony/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krisque/Knowtrex/opony/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krisque/Knowtrex/opony/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krisque/Knowtrex/opony/.venv/lib/python3.12/site-packages/camoufox/__main__.py", line 89, in fetch
    download_mmdb()
  File "/Users/krisque/Knowtrex/opony/.venv/lib/python3.12/site-packages/camoufox/locale.py", line 212, in download_mmdb
    webdl(
  File "/Users/krisque/Knowtrex/opony/.venv/lib/python3.12/site-packages/camoufox/pkgman.py", line 436, in webdl
    response.raise_for_status()
  File "/Users/krisque/Knowtrex/opony/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/P3TERX/GeoLite.mmdb/releases/download/2024.12.16/GeoLite2-City.mmdb
```

### To Reproduce:

just camoufox fetch

### Version:

Pip package:	v0.4.3
Camoufox:	v133.0-beta.19 (Up to date!)

**Comment by chrisemke** [comment]
looks like this: #134
but not seems to be fixed

**Comment by chrisemke** [comment]
duplicate of #134 thanks, closing

**Comment by daijro** [comment]
Hello, you might want to update to the latest version:

```bash
pip install -U camoufox
```
