### ISSUE TITLE
[bug] Camoufox v130.0.1-beta.9 throws errors

### ISSUE THREAD

**Issue by tobwen** [daijro/camoufox#20]
I was so stupid to fetch the latest version, now I'm getting this:

Pip package: v0.2.2
Camoufox: v130.0.1-beta.9
OS: Debian Bookworm

``` Py
# venv/bin/camoufox test
Traceback (most recent call last):
  File "/home/tobwen/camoufox/venv/bin/camoufox", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/tobwen/camoufox/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobwen/camoufox/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/tobwen/camoufox/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobwen/camoufox/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobwen/camoufox/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobwen/camoufox/venv/lib/python3.11/site-packages/camoufox/__main__.py", line 99, in test
    with Camoufox(headless=False, env=environ) as browser:
  File "/home/tobwen/camoufox/venv/lib/python3.11/site-packages/camoufox/sync_api.py", line 23, in __enter__
    self.browser = NewBrowser(self._playwright, **self.launch_options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobwen/camoufox/venv/lib/python3.11/site-packages/camoufox/sync_api.py", line 114, in NewBrowser
    return playwright.firefox.launch(**opt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobwen/camoufox/venv/lib/python3.11/site-packages/playwright/sync_api/_generated.py", line 14723, in launch
    self._sync(
  File "/home/tobwen/camoufox/venv/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 109, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/home/tobwen/camoufox/venv/lib/python3.11/site-packages/playwright/_impl/_browser_type.py", line 95, in launch
    Browser, from_channel(await self._channel.send("launch", params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobwen/camoufox/venv/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tobwen/camoufox/venv/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/home/tobwen/camoufox/venv/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error:
```

**Comment by daijro** [comment]
Hello, I can't seem to reproduce this locally.

Did it return any other Browser logs?

Similar to this:
```
Browser logs:

<launching> /root/.cache/camoufox/camoufox-bin -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-OuqmYs -juggler-pipe -start-debugger-server 51723 -silent
<launched> pid=1045
[pid=1045][err] ...
```

**Comment by tobwen** [comment]
Oh sorry, I closed this because it was my own fault: I forgot to set the the DISPLAY variable.
