### ISSUE TITLE
error in new python version

### ISSUE THREAD

**Issue by francadossantosjoaofelipe35** [daijro/camoufox#24]
PS C:\Users\joao\Documents> python .\solver.py
browser-helper-file.json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/? bytes ?                                                                                                                                                                                    
header-network.json      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/? bytes ?                                                                                                                                                                                    
headers-order.json       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/? bytes ?                                                                                                                                                                                    
input-network.json       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/? bytes ?                                                                                                                                                                                    
fingerprint-network.json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/? bytes ?
Traceback (most recent call last):
  File "C:\Users\joao\AppData\Local\Programs\Python\Python312\Lib\site-packages\browserforge\download.py", line 60, in web_fileobj
    async with session.stream('GET', url, follow_redirects=True, timeout=120) as resp:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseClient.stream() got an unexpected keyword argument 'follow_redirects'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joao\Documents\solver.py", line 1, in <module>
    from camoufox.sync_api import Camoufox
  File "C:\Users\joao\AppData\Local\Programs\Python\Python312\Lib\site-packages\camoufox\__init__.py", line 2, in <module>
    from .async_api import AsyncCamoufox, AsyncNewBrowser
  File "C:\Users\joao\AppData\Local\Programs\Python\Python312\Lib\site-packages\camoufox\async_api.py", line 3, in <module>
    from browserforge.fingerprints import Fingerprint, Screen
  File "C:\Users\joao\AppData\Local\Programs\Python\Python312\Lib\site-packages\browserforge\fingerprints\__init__.py", line 3, in <module>
    DownloadIfNotExists()
  File "C:\Users\joao\AppData\Local\Programs\Python\Python312\Lib\site-packages\browserforge\download.py", line 159, in DownloadIfNotExists
    Download()
  File "C:\Users\joao\AppData\Local\Programs\Python\Python312\Lib\site-packages\browserforge\download.py", line 150, in Download
    asyncio.run(AsyncDownload(headers=headers, fingerprints=fingerprints))
  File "C:\Users\joao\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\joao\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joao\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\joao\AppData\Local\Programs\Python\Python312\Lib\site-packages\browserforge\download.py", line 145, in AsyncDownload
    await downloader.download(headers=headers, fingerprints=fingerprints)
  File "C:\Users\joao\AppData\Local\Programs\Python\Python312\Lib\site-packages\browserforge\download.py", line 137, in download
    await asyncio.gather(*tasks)
  File "C:\Users\joao\AppData\Local\Programs\Python\Python312\Lib\site-packages\browserforge\download.py", line 109, in _download_and_extract
    await self._extract_json_from_zip(url, path, progress, task_id, session)
  File "C:\Users\joao\AppData\Local\Programs\Python\Python312\Lib\site-packages\browserforge\download.py", line 96, in _extract_json_from_zip
    async for chunk in self.web_fileobj(url, progress, task_id, session):
  File "C:\Users\joao\AppData\Local\Programs\Python\Python312\Lib\site-packages\browserforge\download.py", line 66, in web_fileobj
    except httpx.ConnectError as e:
           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'httpx' has no attribute 'ConnectError'

**Comment by francadossantosjoaofelipe35** [comment]
solved with pip install httpx --upgrade
