### ISSUE TITLE
[GeoIP] camoufox.exceptions.InvalidIP: Failed to get IP address

### ISSUE THREAD

**Issue by tobwen** [daijro/camoufox#42]
### Describe the bug:
I know that Playwright doesn't support `socks` proxies with auth, so I had to go for `https` - but `GeoIP` failed!

It works with `http` only (my proxy supports them all)

### Screenshots:
```
Traceback (most recent call last):
  File "/root/test/browser_test.py", line 72, in <module>
    print(run_test(1)[1])
          ^^^^^^^^^^^^
  File "/root/test/browser_test.py", line 41, in run_test
    with Camoufox(**CONFIG["parameters"]) as browser:
  File "/root/test/venv/lib/python3.11/site-packages/camoufox/sync_api.py", line 29, in __enter__
    self.browser = NewBrowser(self._playwright, **self.launch_options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/test/venv/lib/python3.11/site-packages/camoufox/sync_api.py", line 130, in NewBrowser
    opt = get_launch_options(**_clean_locals(locals()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/test/venv/lib/python3.11/site-packages/camoufox/utils.py", line 398, in get_launch_options
    geoip = public_ip(Proxy(**proxy).as_string())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/test/venv/lib/python3.11/site-packages/camoufox/ip.py", line 113, in public_ip
    raise InvalidIP("Failed to get IP address")
camoufox.exceptions.InvalidIP: Failed to get IP address
```

### To Reproduce:
``` python
CONFIG = {
    "parameters": {
        "block_images": True,
        "geoip": True,
        "headless": False,
        "humanize": True,
        "locale": "de-DE",
        "proxy": {
            "server": "https://xxx.xxx.107.120:6505",
            "username": "3432434",
            "password": "p2dL342alW",
        },
        "firefox_user_prefs": {
            "permissions.default.image": 2,
            "intl.accept_languages": "de,en-US,en",
        }
    }
}

 with Camoufox(**CONFIG["parameters"]) as browser:
    with browser.new_context(proxy=CONFIG["parameters"]["proxy"], ignore_https_errors=True) as context:
```

### Version:
```
Camoufox: v130.0.1-beta.11 (Up to date!)
```

**Comment by tobwen** [comment]
Hacking around in `ip.py`

```
equests.exceptions.ProxyError: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:992)'))))
```

**Comment by tobwen** [comment]
Yop, proxy was broken... I'm using ["glider" ](https://github.com/nadoo/glider) now to connect Camoufox via `HTTP` locally and proxy it to `socks5`.

**Comment by tobwen** [comment]
Sigh!

```
  File "/root/test/venv/lib/python3.11/site-packages/requests/adapters.py", line 282, in proxy_manager_for
    manager = self.proxy_manager[proxy] = SOCKSProxyManager(
                                          ^^^^^^^^^^^^^^^^^^
  File "/root/test/venv/lib/python3.11/site-packages/requests/adapters.py", line 64, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")
requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.
```
