### ISSUE TITLE
geoip=True seems to fail for authenticated proxies

### ISSUE THREAD

**Issue by CSorrel58** [daijro/camoufox#57]
### Describe the bug:

It seems like when trying to use `geoip=True` that the generic geoip will fail to get the IP, seeminlgy because it isn't authenticating? Removing `geoip=True` allows the auth to load successfully

This has happened with oxylabs and smartproxy using the same proxy dict for both generic playwright, camoufox with no geoip, and the camoufox with geoip=True. it only fails on the third one

### To Reproduce:

Successful:
```
proxy = self.proxy_manager.get_random_proxy()
            self.last_used_proxy = proxy
            return {
                "server": proxy.host,
                "username": proxy.auth[0],
                "password": proxy.auth[1],
            }
self.browser = await AsyncCamoufox(proxy=self.proxy).start()
```
Failure
```
proxy = self.proxy_manager.get_random_proxy()
            self.last_used_proxy = proxy
            return {
                "server": proxy.host,
                "username": proxy.auth[0],
                "password": proxy.auth[1],
            }
self.browser = await AsyncCamoufox(proxy=self.proxy, geoip=True).start()
```
leads to this error
```
Traceback (most recent call last):
  File "/Users/clintonsorrel/Documents/GitHub/sensing/sites/walmart/spiders/walmart_search.py", line 140, in run_scraper_tasks
    zipcoded_page, browser = await create_unblocked_session(
  File "/Users/clintonsorrel/Documents/GitHub/sensing/sdk/walmart/session.py", line 30, in create_unblocked_session
    await browser.create_browser()
  File "/Users/clintonsorrel/Documents/GitHub/sensing/sdk/base/camoufox_browser.py", line 79, in create_browser
    self.browser = await AsyncCamoufox(geoip=True,proxy=self.proxy).start()
  File "/Users/clintonsorrel/Library/Caches/pypoetry/virtualenvs/sensing-xL2anXPs-py3.10/lib/python3.10/site-packages/playwright/async_api/_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "/Users/clintonsorrel/Library/Caches/pypoetry/virtualenvs/sensing-xL2anXPs-py3.10/lib/python3.10/site-packages/camoufox/async_api.py", line 29, in __aenter__
    self.browser = await AsyncNewBrowser(_playwright, **self.launch_options)
  File "/Users/clintonsorrel/Library/Caches/pypoetry/virtualenvs/sensing-xL2anXPs-py3.10/lib/python3.10/site-packages/camoufox/async_api.py", line 85, in AsyncNewBrowser
    opt = from_options or launch_options(headless=headless, debug=debug, **kwargs)
  File "/Users/clintonsorrel/Library/Caches/pypoetry/virtualenvs/sensing-xL2anXPs-py3.10/lib/python3.10/site-packages/camoufox/utils.py", line 515, in launch_options
    geoip = public_ip(Proxy(**proxy).as_string())
  File "/Users/clintonsorrel/Library/Caches/pypoetry/virtualenvs/sensing-xL2anXPs-py3.10/lib/python3.10/site-packages/camoufox/ip.py", line 39, in as_string
    schema, url, port = self.parse_server(self.server)
  File "/Users/clintonsorrel/Library/Caches/pypoetry/virtualenvs/sensing-xL2anXPs-py3.10/lib/python3.10/site-packages/camoufox/ip.py", line 35, in parse_server
    raise InvalidProxy(f"Invalid proxy server: {server}")
camoufox.exceptions.InvalidProxy: Invalid proxy server: 156.67.0.122:60000
```
### Version:
```
Pip package:    v0.3.3
Camoufox:       v130.0.1-beta.13 (Up to date!)
```
Run `python -m camoufox version` in your terminal and paste the output here.

**Comment by CSorrel58** [comment]
Confimred it does seem to be whatever process checks for ip because this solved it - hardcoding ip instead of using `True` to find it
```

            ip_address = self.proxy['server'].split(":")[0]
            logging.info(ip_address)
            self.browser = await AsyncCamoufox(geoip=ip_address,proxy=self.proxy).start()
```

**Comment by daijro** [comment]
Hello,

I believe this issue happens because Camoufox expects a schema for the proxy:

```python
proxy={
    'server': "http://123.34.56.78:8080",
    },
)
```

By any chance, you were passing the server without the schema?

**Comment by daijro** [comment]
As of 0.3.4, the proxy schema should default to HTTP if not provided in the server key. I believe this was causing the issue.

Let me know if you're still having trouble with it. :+1:
